### ISSUE TITLE
[Bug/Feature request] Currency convertor returns values after a small delay

### ISSUE THREAD

**Issue by rp1231** [deefrawley/Flow.Launcher.Plugin.Currency#10]
Bug/Feature request hybrid for the currency convertor plugin.

Currently the currency convertor has a small delay before it returns the converted value.

I used to use a plugin on Wox which used to give instant results.

Wanted to ask if the same would be possible in the currency convertor plugin included with flow.

Thanks.

**Comment by deefrawley** [comment]
Sure, I'll look in to regular background jobs. If not the setting is a great idea - python plugins having access to a settings page is relatively new so I haven't implemented that yet. Was thinking of having a setting where you can set your currency and if only one currency code is entered it defaults to that.

**Comment by rp1231** [comment]
Just wanted to add that there is a minute delay even when the xml is updated.
I don't know if this is because the plugin starts calculating the difference between the two currencies
when the second currency is entered.

Here is the link for the plugin that I used on Wox and it has instantaneous results:
https://github.com/encyclist/CurrencyConversion
This one gives a list of results the moment the first currency is entered.

Not sure if you would be concerned with such a minute delay.
But have linked to the plugin for reference, 
Just in case it would be something you would be interested in looking at.

Thanks

**Comment by deefrawley** [comment]
Hmmm, it would seem there may be something wrong with your install. The plugin takes 4 seconds to update the file on my PC and subsequent calls are near instantaneous. The plugin you listed also goes and downloads a rates file from the internet to convert.
Are other Flow python plugins slow for you? Are you using your own Python install or letting Flow download it?

**Comment by rp1231** [comment]
I'm using my own Python install.

The difference I'm talking about is a very minute difference.
It's the difference between instantaneous and near instantaneous.
Even when the xml is updated, It takes a second for the converted value to show up.

**Comment by deefrawley** [comment]
The general converter uses a hardcoded conversion table so doesn't download anything. For the currency one I think the best thing is to set the XML file timeout to longer with a setting so it uses the local file instead of downloading for longer. I'll work on it over the christmas break and also see if I can optimise the code further as well..

**Comment by deefrawley** [comment]
The time it waits before refreshing the rates file is now configurable so you can have less downloading but with the current framework there is no way to update the rates file in the background so there is still the delay when it does. The new flox library I am using is being updated constantly so if this becomes possible, I'll add it in.
