### ISSUE TITLE
错误-ParseError('no element found: line 1, column 0')

### ISSUE THREAD

**Issue by Jerry4159** [deefrawley/Flow.Launcher.Plugin.Currency#12]
尝试使用时出现该信息
The error message when I'm trying to use it.

**Comment by deefrawley** [comment]
发生错误时您执行了什么操作？你能下载货币文件吗？
What were you doing when the error occurred? Can you download the currency file?

**Comment by Jerry4159** [comment]
我输入了 cc 50 CNY USD，并没有显示结果，而是这个。如何确认我是否下载了货币文件？
I typed cc 50 CNY USD, but no results came out but this. How can I confirm that I have downloaded the currency file?

**Comment by Jerry4159** [comment]
再次尝试已可以正常使用，暂时不明原因。
Now it works, don't know what happened before.

**Comment by deefrawley** [comment]
该插件需要下载费率转换文件。 当前版本不能很好地处理错误。 很快就会有一个新的更新来改善这一点。
The plugin requires a rate conversion file to be downloaded. The current version does not handle errors very well. There will be a new update soon to improve this.

**Comment by deefrawley** [comment]
更好的错误处理现在包含在 v2.0 中
Better error handling now included in v2.0
