### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by Zeroto521** [deefrawley/Flow.Launcher.Plugin.Currency#3]
https://github.com/deefrawley/Flow.Launcher.Plugin.Currency/blob/e31b8d67d72901d601b2aabd9e5900ee127a6a2a/LICENSE#L3

I saw `Flow.Launcher.Plugin.Currency` own to `Flow-Launcher`.

Are there some mistakes?

![image](https://user-images.githubusercontent.com/25895405/108210726-e22af100-7166-11eb-92fb-d86ae3c4320d.png)

`Flow.Launcher.Plugin.PythonTemplate` rep has **two** `LICENSE`.

- [Flow.Launcher.Plugin.PythonTemplate/LICENSE](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.PythonTemplate/blob/master/LICENSE) means the rep (template) own to `Flow-Launcher`.
- [Flow.Launcher.Plugin.PythonTemplate/Flow.Launcher.Plugin.PythonTemplate/LICENSE](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.PythonTemplate/blob/master/Flow.Launcher.Plugin.PythonTemplate/LICENSE) means the plugin own to the plugin author who wrote. And this file is **empty**. I put it just to tell the developer doesn't forget to add license information.

So do you really want to let this plugin copyright own to `Flow-Launcher`?

**Comment by deefrawley** [comment]
Thanks for letting me know. I'll check and update the license.
