### ISSUE TITLE
"cc" not being registered 

### ISSUE THREAD

**Issue by pranavburnwal** [deefrawley/Flow.Launcher.Plugin.Currency#4]
The command 'cc' is not being registered. It used to work in Wox. 

![image](https://user-images.githubusercontent.com/15976005/108472912-5a9ec880-72b3-11eb-89cf-1883d0b9ffa7.png)

![image](https://user-images.githubusercontent.com/15976005/108472963-68ece480-72b3-11eb-8358-a1b12dbbe8e8.png)

Flow v 1.7.1

Please let me know what details you need for the debug.

**Comment by pranavburnwal** [comment]
@deefrawley

**Comment by deefrawley** [comment]
Hey @pranavburnwal  - have you installed the Python dependencies in the requirements.txt file via the Python pip command?

**Comment by deefrawley** [comment]
@pranavburnwal  any update? If not I'll close the issue.

**Comment by pranavburnwal** [comment]
Let me double check and revert

**Comment by deefrawley** [comment]
No further feedback so closing this
