### ISSUE TITLE
Got FileNotFoundError because missing `messages.mo` files

### ISSUE THREAD

**Issue by pc223** [deefrawley/Flow.Launcher.Plugin.Currency#7]
The new release have this error, because it's missing `messages.mo` files in `Currency Converter-1.2.0\plugin\translations`

```
2021Jun23 - 12:56:32.3180953+07:00 - DEBUG - PluginManager - QueryForPluginAsync|"Cost for Currency Converter <393ms>"
2021Jun23 - 12:56:32.6906172+07:00 - ERROR - JsonRPCPlugin - ExecuteAsync|"Traceback (most recent call last):
  File "C:\Users\user1\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-1.2.0\main.py", line 9, in <module>
    from plugin import Main
  File "C:\Users\user1\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-1.2.0\plugin\__init__.py", line 24, in <module>
    from plugin.ui import Main
  File "C:\Users\user1\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-1.2.0\plugin\ui.py", line 10, in <module>
    from plugin.extensions import _
  File "C:\Users\user1\AppData\Roaming\FlowLauncher\Plugins\Currency Converter-1.2.0\plugin\extensions.py", line 8, in <module>
    translation = gettext.translation("messages", "plugin/translations/", languages=[LOCAL])
  File "gettext.py", line 588, in translation
FileNotFoundError: [Errno 2] No translation file found for domain: 'messages'
```

@jjw24  Can CI deal with this automatically? Probably have to run command like this:

```
sudo apt-get install -y gettext
msgfmt messages.po -o messages.mo
```

**Comment by deefrawley** [comment]
The Python template uses Babel which is in the requirements-dev.txt. Compiling the message files to the binaries (`.mo` to `.po`) has been a manual task for me so it would be good to include it as a CI step just to make sure it is there.

**Comment by jjw24** [comment]
how come you have a requirements-dev.txt lol, why not put them in requirements.txt. Wouldnt this solve the problem?

**Comment by deefrawley** [comment]
It's part of the template. And even if Babel was in the requirements.txt and the CI installed the library, it's still a separate step to compile the translation files if they haven't been already. I suppose the plugin code could check at execution for the existence of the files and then do the compiling then via the Python library, but I think the ci option is cleaner. The only possible down side is that for Python plugins that don't have translations, their ci script would need to omit this step or run a different yaml script?

**Comment by pc223** [comment]
I think you can simply add to github workflow something similar to this:

(You use Babel instead of gettext maybe use a different commands, compile_catalog?)

```
      - name: Install dependencies
        run: |
          sudo apt-get install -y gettext
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt -t ./lib
          zip -r Flow.Launcher.Plugin.Currency.zip . -x '*.git*'
      - name: Compile .po to .mo
        run: |
          msgfmt plugin/translations/en/LC_MESSAGES/messages.po -o plugin/translations/en/LC_MESSAGES/messages.mo
          msgfmt plugin/translations/zh/LC_MESSAGES/messages.po -o plugin/translations/zh/LC_MESSAGES/messages.mo

```

**Comment by jjw24** [comment]
@pc223 @deefrawley  check the pr, should be what we are after

**Comment by pc223** [comment]
> @pc223 @deefrawley check the pr, should be what we are after

Tested, seems solid! 👍
